### ISSUE TITLE
not compatible with 1.15.2

### ISSUE THREAD

**Issue by barecool** [AlvinVrolijk/CompassInfo#1]
java.lang.NoSuchMethodError: org.bukkit.entity.Player.sendActionBar(Ljava/lang/String;)V
at nl.alvinvrolijk.compassinfo.CompassInfo.lambda$onEnable$0(CompassInfo.java:28) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by AlvinVrolijk** [comment]
It is, but i forgot to mention it depends on Paper1

**Comment by AlvinVrolijk** [comment]
*Paper
